// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/authorization/permission/permission.proto

package permission

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PermissionClient is the client API for Permission service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionClient interface {
	Fetch(ctx context.Context, in *FetchRequestPermission, opts ...grpc.CallOption) (*FetchResponsePermission, error)
	Store(ctx context.Context, in *PermissionRequest, opts ...grpc.CallOption) (*MainResponsePermission, error)
	FindByID(ctx context.Context, in *FindByIDPermissionRequest, opts ...grpc.CallOption) (*MainResponsePermission, error)
	Update(ctx context.Context, in *PermissionRequest, opts ...grpc.CallOption) (*MainResponsePermission, error)
	Delete(ctx context.Context, in *FindByIDPermissionRequest, opts ...grpc.CallOption) (*MainResponsePermission, error)
}

type permissionClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionClient(cc grpc.ClientConnInterface) PermissionClient {
	return &permissionClient{cc}
}

func (c *permissionClient) Fetch(ctx context.Context, in *FetchRequestPermission, opts ...grpc.CallOption) (*FetchResponsePermission, error) {
	out := new(FetchResponsePermission)
	err := c.cc.Invoke(ctx, "/permission.Permission/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) Store(ctx context.Context, in *PermissionRequest, opts ...grpc.CallOption) (*MainResponsePermission, error) {
	out := new(MainResponsePermission)
	err := c.cc.Invoke(ctx, "/permission.Permission/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) FindByID(ctx context.Context, in *FindByIDPermissionRequest, opts ...grpc.CallOption) (*MainResponsePermission, error) {
	out := new(MainResponsePermission)
	err := c.cc.Invoke(ctx, "/permission.Permission/FindByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) Update(ctx context.Context, in *PermissionRequest, opts ...grpc.CallOption) (*MainResponsePermission, error) {
	out := new(MainResponsePermission)
	err := c.cc.Invoke(ctx, "/permission.Permission/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) Delete(ctx context.Context, in *FindByIDPermissionRequest, opts ...grpc.CallOption) (*MainResponsePermission, error) {
	out := new(MainResponsePermission)
	err := c.cc.Invoke(ctx, "/permission.Permission/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionServer is the server API for Permission service.
// All implementations must embed UnimplementedPermissionServer
// for forward compatibility
type PermissionServer interface {
	Fetch(context.Context, *FetchRequestPermission) (*FetchResponsePermission, error)
	Store(context.Context, *PermissionRequest) (*MainResponsePermission, error)
	FindByID(context.Context, *FindByIDPermissionRequest) (*MainResponsePermission, error)
	Update(context.Context, *PermissionRequest) (*MainResponsePermission, error)
	Delete(context.Context, *FindByIDPermissionRequest) (*MainResponsePermission, error)
	mustEmbedUnimplementedPermissionServer()
}

// UnimplementedPermissionServer must be embedded to have forward compatible implementations.
type UnimplementedPermissionServer struct {
}

func (UnimplementedPermissionServer) Fetch(context.Context, *FetchRequestPermission) (*FetchResponsePermission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedPermissionServer) Store(context.Context, *PermissionRequest) (*MainResponsePermission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedPermissionServer) FindByID(context.Context, *FindByIDPermissionRequest) (*MainResponsePermission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByID not implemented")
}
func (UnimplementedPermissionServer) Update(context.Context, *PermissionRequest) (*MainResponsePermission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPermissionServer) Delete(context.Context, *FindByIDPermissionRequest) (*MainResponsePermission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPermissionServer) mustEmbedUnimplementedPermissionServer() {}

// UnsafePermissionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionServer will
// result in compilation errors.
type UnsafePermissionServer interface {
	mustEmbedUnimplementedPermissionServer()
}

func RegisterPermissionServer(s grpc.ServiceRegistrar, srv PermissionServer) {
	s.RegisterService(&Permission_ServiceDesc, srv)
}

func _Permission_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequestPermission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).Fetch(ctx, req.(*FetchRequestPermission))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).Store(ctx, req.(*PermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_FindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIDPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).FindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/FindByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).FindByID(ctx, req.(*FindByIDPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).Update(ctx, req.(*PermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIDPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).Delete(ctx, req.(*FindByIDPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Permission_ServiceDesc is the grpc.ServiceDesc for Permission service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Permission_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "permission.Permission",
	HandlerType: (*PermissionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _Permission_Fetch_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _Permission_Store_Handler,
		},
		{
			MethodName: "FindByID",
			Handler:    _Permission_FindByID_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Permission_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Permission_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/authorization/permission/permission.proto",
}
